# Use the latest 2.1 version of CircleCI pipeline process engine.
version: 2.1

orbs:
  python: circleci/python@1.5.0

# Define a job to be invoked later in a workflow.
jobs:
  build-job:
    docker:
      - image: ubuntu
    steps:
      - run:
          name: Install docker
          command: apt-get install docker-ce docker-ce-cli containerd.io docker-compose-plugin
      - run:
          name: Run construction
          command: docker build -t davcorsar/linear-regression-house-pricing:latest .
      - run:
          name: Run test
          command: docker run davcorsar/linear-regression-house-pricing
      - run:
          name: Run release
          command: ID=$(sudo docker container ps -l -q); docker commit $ID davcorsar/linear-regression-house-pricing:latest; docker push davcorsar/linear-regression-house-pricing:latest

workflows:
  sample:
    # Inside the workflow, I defined the jobs you want to run.
    jobs:
      - build-job
