name: Docker Image CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build -t davcorsar/linear-regression-house-pricing:latest .
    - name: Run the Docker image
      run: docker run davcorsar/linear-regression-house-pricing
    - name: Login to DockerHub
      run: docker login -u "myusername" -p "mypassword" docker.io
    - name: Push the Docker image
      run: docker push davcorsar/linear-regression-house-pricing:latest



  #test:

   # runs-on: ubuntu-latest

    #steps:
#    - uses: actions/checkout@v3
 #   - name: Run the Docker image
  #    run: docker run davcorsar/linear-regression-house-pricing

#  push:

 #   runs-on: ubuntu-latest

  #  steps:
   # - uses: actions/checkout@v3
    #- name: Push the Docker image
     # run: docker push davcorsar/linear-regression-house-pricing:latest

